### ISSUE TITLE
A-Weighting filter

### ISSUE THREAD

**Issue by jes-carr** [markert/fili.js#10]
Is it possible to implement an A-weighting filter with this library? http://www.diracdelta.co.uk/science/source/a/w/aweighting/source.html#.VtRsF5MrJE4

**Comment by markert** [comment]
I added the algorithm posted here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4331191/

This will give you the filter from the example:

var iirCalculator = new Fili.CalcCascades();
var coeffsBessel = iirCalculator.aweighting({
      order: 1,
      characteristic: 'butterworth',
      Fs: 1000,
      Fc: 250
    });
var filterButterworth = new Fili.IirFilter(coeffsButterworth);
