### ISSUE TITLE
BW units

### ISSUE THREAD

**Issue by iPhaeton** [markert/fili.js#13]
Hi. We are trying to apply an iir bandpass butterworth filter filter to a sinusoidal wave with frequency of 1000Hz and calculate RMS before and after applying the filer.
A filter with these params
`const filterCoeffs = iirCalculator.bandpass({#
    order: 3,
    characteristic: 'butterworth',
    Fs: 44100,
    Fc: 800,
    preGain: false,
});`
yields an expected result: RMS after filtering by 1000 Hz changes very little, for other frequencies it drops significantly.
But if we try to set BW, like this
`const filterCoeffs = iirCalculator.bandpass({
    order: 3,
    characteristic: 'butterworth',
    Fs: 44100,
    Fc: 800,
    BW: 100,
    preGain: false,
});`
we get the same RMS before and after filtering for all frequencies. Are we missing something here? Is a unit for BW Hz or kHz or something else?

**Comment by markert** [comment]
Hi,
the bandwifth is defined as in the audio EQ cookbook (that´s where I got the formulars from):

> BW, the bandwidth in octaves (between -3 dB frequencies for BPF
>         and notch or between midpoint (dBgain/2) gain frequencies for
>         peaking EQ)

100 octaves would be quite a lot. It makes it flat over the whole frequency range which leads to the same RMS before and after filtering.

**Comment by iPhaeton** [comment]
Thanks a lot
