### ISSUE TITLE
Using coefficients more than once causes filters to add together

### ISSUE THREAD

**Issue by tarocco** [markert/fili.js#16]
I have a codepen script to demonstrate the issue: [codepen.io/tarocco/pen/Xzzzdq](https://codepen.io/tarocco/pen/Xzzzdq)

On line 80 if you change `iirFilterCoeffsB` to `iirFilterCoeffsA`, the filters _should_  just use the same coefficients, but behave independently otherwise. Instead, their inputs seem to just add together into the same filter buffer. In this example, the mouse-rotated sphere rotates diagonally if you change it to use the same coefficients object for both filters.

**Comment by markert** [comment]
You are right. I just had a short look at the fili code. The state of the filter is saved together with the coefficients. It should be saved in the filter instance. I will change that.

**Comment by markert** [comment]
Changed it. Should work with version 2.0.1

**Comment by markert** [comment]
Guess it's fixed. Nice demo by the way. However, a Bessel filter would fit the purpose better.
