### ISSUE TITLE
Zero-lag butterworth filter

### ISSUE THREAD

**Issue by etoshey** [markert/fili.js#30]
Hi, I hope you are doing well.
I am passing the signal through the Butterworth low-pass filter twice, first, in the forward direction, and the second, passing the reversed filtered data. but there is a shift in my output.
Best regards,

![Capture](https://user-images.githubusercontent.com/13487923/163668544-d94d1ec7-5de7-4f44-8c7f-c83798cb68e0.PNG)
.

**Comment by markert** [comment]
Without understanding the setup completely, I would guess that you see the normal filter delay.

**Comment by etoshey** [comment]
OK, thank you for your comment.
This is my setup:
    var iirFilterCoeffs = iirCalculator.lowpass({
        order: 2, 
        characteristic: 'butterworth',
        Fs: 500, 
        Fc: 15             
    });

**Comment by markert** [comment]
If you do a forward-backward filtering to remove the phase shift, I would expect the result that you are seeing. You will see a shift in the forward direction and when doing the backward filtering, the shift will disappear and the samples will match the input samples.

**Comment by etoshey** [comment]
Thank you
