### ISSUE TITLE
Is it possible to add Linkwitz-Riley filters?

### ISSUE THREAD

**Issue by exislow** [markert/fili.js#31]
First of all: Great work! I really like this package.

In my opionion one very important filter is missing: [Linkwitz-Riley](https://en.wikipedia.org/wiki/Linkwitz%E2%80%93Riley_filter)

@markert: Is it possible, that to extend your table values for this filter? I have already found the Q-values: https://github.com/HEnquist/camilladsp/blob/master/filterfunctions.md

Thanks!

**Comment by markert** [comment]
I just had a look at LR filters. I am not that familiar with them. You should be able to build LR filters with fili.js already. A LR filter is just a parallel setup of hp and lp Butterworth filters. You could also add the outputs. What you can see from the table you shared is that a 4th order LR filter uses the same Q values for cascading that 2 2nd order Butterworth filters would use.

**Comment by exislow** [comment]
@markert: To be honest I am quite new in this topic and not really into the mathematical details, yet. This will take a while, I guess. I recently screened your code and I guess, if somebody is into the mathematical details, it would take this person just a few minutes to extend the fili.js code to implement the Linkwitz-Riley filters, which are very commonly used in the digital sound processing domain.

Would you be up to to implement this filters with me together or at least tell me how to cascade 2 2nd order Butterworth filters? Also a 2nd order Linkwitz-Riley filter uses something like an Sallen Key filter. This is not implemented, yet, in your code, is it?

I would really appreciate some help. Thank you in advance. This extension request is for some improvements in the freeDSP Aurora project.

**Comment by exislow** [comment]
@markert: I would really appreciate some help. Thanks!
