### ISSUE TITLE
FFT 

### ISSUE THREAD

**Issue by tiagoagre** [markert/fili.js#6]
Hi.

I´m using FILI to apply some LP and HP filters, everything is working great, very easy to use.

But i dont know how to generate FFT values in order to create a FFT window like this one (the graphical part is up to me): 
https://dl.dropboxusercontent.com/u/15802004/fft_ex.png
Looking for FILI source, magnitude, phase are available in fft, but all requires additional parameters, and i cant find any info about this additional parameters.

Is it possible to provide a guidance to generate fft values?

Example for testing:

var sps = 40;
var seconds = 300;
var buffer= [];

for (var cnt = 0; cnt < (sps \* seconds); cnt++) {
  var randomValue = Math.floor(Math.random() \* 201) - 100;
  buffer.push(randomValue);
}

Thanks for FILI.

Best Regards.
Tiago.

**Comment by markert** [comment]
The FFT calculation returns an Object {re: [], im: []} complex numbers.

```
var fftArray = [];
var cnt = 0;
var fft = new Fft(1024);
for (cnt = 0; cnt < 1024; cnt++) {
  fftArray.push(Math.random());
}
var res = fft.forward(fftArray, 'hanning');
var db = fft.magToDb(fft.magnitude(res)); // Array of 1024 dB values.
var phase = fft.phase(res); // Array of 1024 phase values
```

If you like to set 0dB, you will have to write your own function that scales the magnitude.

Note that the fft radix must always be a 2^n value.

**Comment by tiagoagre** [comment]
Hi.

Following your tips i manage to generate a fft chart, pretty happy with the results.

Comparing with real data..
https://dl.dropboxusercontent.com/u/15802004/fft_compare.png

For now this fulfill my needs :+1: 

Thanks!

**Comment by markert** [comment]
You can increase the detail of the FFT by raising the number of points calculated (e.g. 8192 or 262144). If your sample does not have enough values, use zero padding (fill the rest with 0).

Have fun.
