### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by jwynveen** [markert/fili.js#7]
I pulled this into a very basic node.js app through npm to do some testing. When I started the project I got errors in the firFilter.js and iirFilter.js files with the utils require at the top. 

```
/Projects/test/node_modules/fili/src/firFilter.js:3
var {
    ^
SyntaxError: Unexpected token {
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Projects/test/node_modules/fili/index.js:8:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

It doesn't seem to like the syntax for assigning the `require` to an object is valid. I could fix it by changing that require to the below:

```
var runMultiFilter = require('./utils').runMultiFilter,
  complex = require('./utils').complex,
  evaluatePhase = require('./utils').evaluatePhase;
```

Is there some node or js syntax that I'm missing for the current version to build correctly? Or can the npm package get updated with correct syntax?

**Comment by markert** [comment]
You should use the fili.js or fili.min.js from the dist folder. They are generated by the Makefile build which uses babelify and provides backward compatibility with older ecmascript standards. The code snipped gets translated to:

```
var _require = require('./utils');

var runMultiFilter = _require.runMultiFilter;
var complex = _require.complex;
var evaluatePhase = _require.evaluatePhase;
```

fili.js and fili.min.js may be used both in a browser or as a node.js module.

**Comment by liddellj** [comment]
I encountered this issue as well, by simply requiring fili as follows:

``` javascript
import Fili from 'fili';
```

The problem is that by default, `index.js` is pulled in rather than anything from the dist folder - and `index.js` refers to files in the src folder, which use ES6 syntax and therefore require transpiling for ES5 environments. I think adding:

``` javascript
"main": "dist/fili.min.js",
```

To your package.json would fix this. Happy to submit a PR if you like?

**Comment by markert** [comment]
Just submit a PR. I will have a look at it. 

Thanks in advance.
